Repository phlowers/mechaphlowers, pull requests merged in 2025-01, with the labels that each got.

#41 Display the section without insulators and for simple supports
  poetry.lock
  pyproject.toml
  src/mechaphlowers/core/geometry/__init__.py
  src/mechaphlowers/core/geometry/references.py
  src/mechaphlowers/core/models/cable_models.py
  src/mechaphlowers/entities/__init__.py
  src/mechaphlowers/entities/arrays.py
  src/mechaphlowers/entities/frames.py
  src/mechaphlowers/entities/schemas.py
  src/mechaphlowers/plotting/__init__.py
  src/mechaphlowers/plotting/plot.py
  src/mechaphlowers/utils.py
  test/core/geometry/test_reference.py
  test/core/models/test_cable_models.py
  test/entities/test_arrays.py
  test/entities/test_frames.py
  test/plotting/test_line3d.py
Labels: enhancement

#51 solve issue and improve rendering
  docs/developer_guide/documentation.md
  docs/docstring/core/geometry/references.md
  docs/docstring/core/models/cable_models.md
  docs/docstring/entities/arrays.md
  docs/docstring/entities/frames.md
  docs/docstring/entities/schemas.md
  docs/docstring/welcome.md
  docs/index.md
  docs/user_guide/ug_cable_model.md
  mkdocs.yaml
Labels: documentation, technical

#54 SectionArray raise error when sagging properties are not set
  pyproject.toml
  src/mechaphlowers/entities/arrays.py
  test/entities/test_arrays.py
  test/entities/test_frames.py
  test/plotting/test_line3d.py
Labels: bug
